version: "2"
services:
  nginx:
    restart: always
    build: ./nginx
    image: abhishekray07/nginx
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    restart: always
    build: ./web
    image: abhishekray07/web
    expose:
      - "5050"
