version: "2"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  web1:
    build: ./web
    command: npm start
    ports:
      - 3000
  web2:
    build: ./web
    command: npm start
    ports:
      - 3000
